spring:
  application:
    name: Scope

  datasource:
    url: jdbc:postgresql://localhost:5432/scope_db
    username: scope_user
    password: scope_pswd
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect