spring:
  application:
    name: Scope

  datasource:
    url: jdbc:postgresql://localhost:5432/scope_db?TimeZone=Asia/Kolkata
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.posgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect